# Generated by Django 5.0 on 2023-12-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=20)),
                ('semester_code', models.CharField(max_length=10, unique=True)),
                ('semester_data', models.JSONField()),
                ('last_update_datetime', models.DateTimeField()),
            ],
        ),
    ]
